# Generated by Django 5.0.2 on 2024-02-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='send_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начала интервала, в котором отправлять сообщения'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='send_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начала интервала, в котором отправлять сообщения'),
        ),
    ]
